// 로그인한 사용자의 정보를 담는 모델

class Autogenerated {
  int? id;
  String? studentId;
  String? name;
  String? phoneNumber;
  String? email;
  bool? approved;
  String? createdAt;
  String? updatedAt;

  Autogenerated(
      {this.id,
      this.studentId,
      this.name,
      this.phoneNumber,
      this.email,
      this.approved,
      this.createdAt,
      this.updatedAt});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    studentId = json['student_id'];
    name = json['name'];
    phoneNumber = json['phone_number'];
    email = json['email'];
    approved = json['approved'] == 1;
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['student_id'] = studentId;
    data['name'] = name;
    data['phone_number'] = phoneNumber;
    data['email'] = email;
    data['approved'] = approved;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}